# Generated by Django 3.2.16 on 2025-05-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_post/', verbose_name='Изображение'),
        ),
    ]
